### ISSUE TITLE
The modes like /tryme pmode /tryme bmode /tryme emode /tryme kmode doesn't seem to work?

### ISSUE THREAD

**Issue by bobhenl** [Zrips/TryMe#24]
Hi, when I type these cmds it doesn't seem that the new modes are activated. I think that the new modes should be more revisit to let them fully working

**Comment by Zrips** [comment]
Server version? Plugin version?

**Comment by KarlPro123** [comment]
Using TryMe 7.1.1.0 and Paper 1.19.2, these modes are also not working for me. 
Also, when trying to start these modes by force by typing for example /tryme emode to start eat task, it starts mmode (calculations) instead. Using /tryme amode does start all of the tasks though, but nothing happens when I try to complete them.

**Comment by bobhenl** [comment]
same for me, 1.19.3, the plugin version was 7.1.0.6

**Comment by Zrips** [comment]
Should be resolved with latest version

**Comment by MedvedEE** [comment]
Still having the same problem, even with the latest version(7.1.1.2). Now I've found out that if you start the server and call out different modes (tryme qmode, fmode, hmode, pmode) everything works. But if you call out amode, it breaks. Calling out individually qmode,fmode,hmode, it calls out the latest mode that was called with amode, but not the designated mode( hmode doesn't do hangman, but for example, questions). Also, the pmode and bmode no longer register if a person breaks or places a block.
